### ISSUE TITLE
Outdated API features are used!

### ISSUE THREAD

**Issue by SaltyAimbOtter** [BetonQuest/RPGMenu#14]
## Bug report
This plugin uses the old InstructionParseException in BetonQuest that does not exist anymore.

**Spigot version:** `1.12`

**RPGMenu version:** `bundabrg v3.1-preview.1`

**BetonQuest version:** `1.12 devbuilds`

### Description:

```
https://gist.github.com/SaltyAimbOtter/376db8cf2636b6f40502e4b25474f989
```

### How to reproduce:
/q reload on a 1.12+ devbuild of BQ

### Checklist:

- [X] I included all versions (use `/version` command)
- [X] I made sure there aren't duplicates of this report [(use Search)](https://github.com/joblo2213/RPGMenu/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3ABug+)
- [X] I made sure I am using an up-to-date version of RPGMenu
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Wolf2323** [comment]
fixed in 5460003
