### ISSUE TITLE
RPGMenu No Longer Works on New Dev Builds of BQ

### ISSUE THREAD

**Issue by MonzterDev** [BetonQuest/RPGMenu#19]
I received this error when updating to -278
https://pastebin.com/keH7vALL

The plugin no longer seems to function at all. Menus cannot be opened and reloading throws error. Although I can do /rpgmenu list and it displays no menus, so partially functional.

I have reverted back down to -270 and experience no issues.

**Comment by seyfahni** [comment]
Fixed with release `4.0.1`.
