### ISSUE TITLE
Update Notification Display 

### ISSUE THREAD

**Issue by MonzterDev** [BetonQuest/RPGMenu#20]
## Bug report

**Spigot version:** `<!-- 1.16.4 -->`

**RPGMenu version:** `<!-- NEWEST -->`

**BetonQuest version:** `<!-- NEWEST -->`

### Description:

![image](https://user-images.githubusercontent.com/36930553/102910941-5ee06e00-4449-11eb-8e05-0e1f621399fd.png)
Clicking the gray text gives me this linkhttps://github.com/BetonQuest/RPGMenu/releases which seems correct, but the gray text seems incorrect

### Checklist:

- [ ] I included all versions (use `/version` command)
- [X] I made sure there aren't duplicates of this report [(use Search)](https://github.com/joblo2213/RPGMenu/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3ABug+)
- [X] I made sure I am using an up-to-date version of RPGMenu
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by seyfahni** [comment]
Please provide the actual versions instead of latest, so we can also reproduce it at a later date.

**Comment by MonzterDev** [comment]
RPGMenu v4.0.2, sorry for delay I don't look at my Github notifications often

**Comment by seyfahni** [comment]
Then please use the latest version of RPGMenu: `v4.0.3`
https://github.com/BetonQuest/RPGMenu/releases/tag/4.0.3

It contains the fix for it to work with the changed updater in BetonQuest `1.12`.
