### ISSUE TITLE
Refreshing items

### ISSUE THREAD

**Issue by Momonche** [BetonQuest/RPGMenu#7]
Paper version git-Paper-1562 (MC:1.12.2)

RPGMenu 3.0

BetonQuest 2.0-prewiew.9

Hello @joblo2213  !
I try to open a menu2 when I click on a item in menu1, but when the menu2 is open items are not refreshed, I still see items of the menu1.
But the title of the menu is refresh

**Comment by bundabrg** [comment]
Found the issue and have submitted a PR. For the impatient a preview build is [here](https://github.com/bundabrg/RPGMenu/releases/tag/v3.1-preview.1)

**Comment by SaltyAimbOtter** [comment]
Not fixed: https://youtu.be/56dI_HdiSr0

**Comment by bundabrg** [comment]
Redownload release. Sorted I think ;)
